### ISSUE TITLE
Composer installation fails

### ISSUE THREAD

**Issue by johlton** [balemy/ldap-commander#7]
### What steps will reproduce the problem?
A simple `composer install` after a fresh `git clone`. No Docker installation.
### What is the expected result?
The composer installation goes through smoothly.
### What do you get instead?
````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii-widgets 1.0.0 requires yiisoft/cache ^2.0 -> found yiisoft/cache[2.0.0] but it conflicts with your root composer.json require (^1.0).
    - yiisoft/yii-dataview 3.0.x-dev is an alias of yiisoft/yii-dataview dev-master and thus requires it to be installed too.
    - yiisoft/yii-dataview dev-master requires yiisoft/yii-widgets ^1.0 -> satisfiable by yiisoft/yii-widgets[1.0.0].
    - Root composer.json requires yiisoft/yii-dataview ^3.0@dev -> satisfiable by yiisoft/yii-dataview[3.0.x-dev (alias of dev-master)].
````
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 0.5.0
| PHP version      | 8.1
| Operating system | Ubuntu Linux 22.04

Thanks!

**Comment by luke-** [comment]
Can you please try it again? The problem should be fixed now.

**Comment by johlton** [comment]
Thank you, installation runs smoothly now! :)
